### ISSUE TITLE
[BUG] make manifests fails due to controller-gen panic on go 1.22

### ISSUE THREAD

**Issue by sophon-zt** [apecloud/kubeblocks-addons#597]
```
$ go version
go version go1.22.2 darwin/arm64
```

```
$ make manifests
...

Installing controller-gen@v0.12.1...
Successfully installed
/Users/zhangtao/develop/infracreate/kubeblocks_develop/bin/controller-gen rbac:roleName=manager-role crd:generateEmbeddedObjectMeta=true webhook paths="./cmd/manager/...;./apis/...;./controllers/..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100696d14]

goroutine 282 [running]:
go/types.(*Checker).handleBailout(0x14000fd4000, 0x14002d6bd18)
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/check.go:367 +0x9c
panic({0x1009713a0?, 0x100f13f10?})
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x100a3bfd0, 0x100f1c6c0})
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/sizes.go:228 +0x314
go/types.(*Config).sizeof(...)
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/sizes.go:333
go/types.representableConst.func1({0x100a3bfd0?, 0x100f1c6c0?})
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x100a42230, 0x100ee8800}, 0x14000fd4000, 0x100f1c6c0, 0x14002d6b468)
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/const.go:92 +0x138
go/types.(*Checker).representation(0x14000fd4000, 0x14003af6580, 0x100f1c6c0)
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/const.go:256 +0x68
go/types.(*Checker).implicitTypeAndValue(0x14000fd4000, 0x14003af6580, {0x100a3bff8, 0x14000252b60})
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/expr.go:375 +0x304
go/types.(*Checker).assignment(0x14000fd4000, 0x14003af6580, {0x100a3bff8, 0x14000252b60}, {0x1007af560, 0x14})
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/assignments.go:52 +0x23c
go/types.(*Checker).initConst(0x14000fd4000, 0x140037791a0, 0x14003af6580)
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/assignments.go:126 +0x274
go/types.(*Checker).constDecl(0x14000fd4000, 0x140037791a0, {0x100a3eba0, 0x140024b0980}, {0x100a3eba0, 0x140024b09a0}, 0x0)
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/decl.go:490 +0x250
go/types.(*Checker).objDecl(0x14000fd4000, {0x100a47380, 0x140037791a0}, 0x0)
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/decl.go:191 +0x84c
go/types.(*Checker).packageObjects(0x14000fd4000)
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/resolver.go:693 +0x468
go/types.(*Checker).checkFiles(0x14000fd4000, {0x140020ebb90, 0x5, 0x5})
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/check.go:408 +0x164
go/types.(*Checker).Files(...)
        /Users/zhangtao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0x140002814a0, 0x14001465920)
        /Users/zhangtao/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.1/pkg/loader/loader.go:286 +0x2d8
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0x14001465920)
        /Users/zhangtao/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.1/pkg/loader/loader.go:99 +0x44
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0x14001907230, 0x14001465920)
        /Users/zhangtao/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.1/pkg/loader/refs.go:268 +0x304
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x66?)
        /Users/zhangtao/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.1/pkg/loader/refs.go:262 +0x58
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 123
        /Users/zhangtao/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.1/pkg/loader/refs.go:260 +0x230
make: *** [manifests] Error 2
```

**Comment by sophon-zt** [comment]
related bug: https://github.com/kubernetes-sigs/controller-tools/issues/880
